use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set");
    let generated = Path::new(&out_dir).join("generated.rs");
    fs::write(
        generated,
        "pub fn generated_message() -> &'static str { \"generated by build.rs\" }\n",
    )
    .expect("failed to write generated file");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-cfg=tong_build_script");
}

