[package]
name = "tong"
description = "Tong command-line interface"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tong-core = { path = "../tong-core" }
tong-exec = { path = "../tong-exec" }
tong-fetch = { path = "../tong-fetch" }
tong-graph = { path = "../tong-graph" }
tong-rust = { path = "../tong-rust" }
tong-store = { path = "../tong-store" }
semver = "1"
serde = { workspace = true, features = ["derive"] }
toml = "0.8"
clap = { workspace = true }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
flate2 = "1"
tar = "0.4"
